routes/web.php
<?php

use App\Services\EdenAiService;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Route::resource('lottery', \App\Http\Controllers\LotteryDemoController::class);

Route::get('lottery-public-id', function () {
    // test 697fabcf-7a5a-44b8-b78b-3766b1336dd4
    $result = (new EdenAiService)->result('d87741bf-c357-4dd2-9b6e-e7b775eeff9c');

    dd($result);
});

app/Models/Lottery.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Lottery extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function detail()
    {
        return $this->hasMany(LotteryDetail::class, 'lottery_id');
    }

    public function sumTotalPrice()
    {
        $sum = 0;

        foreach ($this->detail as $detail) {
            $sum += floatval($detail->price);
        }

        return $sum;
    }
}

app/Models/LotteryDetail.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class LotteryDetail extends Model
{
    use HasFactory;

    protected $guarded = [];
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/LotteryDemoController.php
<?php

namespace App\Http\Controllers;

use App\Models\Lottery;
use App\Models\LotteryDetail;
use App\Services\EdenAiService;
use Illuminate\Http\Request;

class LotteryDemoController extends Controller
{
    private $service;

    public function __construct(EdenAiService $edenAiService)
    {
        $this->service = $edenAiService;
    }

    public function index()
    {
        $lotteries = Lottery::orderBy('created_at', 'desc')->get();
        return view('lottery.index', compact('lotteries'));
    }

    public function create()
    {
        return view('lottery.create');
    }

    public function store(Request $request)
    {
        $result = $this->service->upload($request->file('file'));
        $lottery = $this->service->store($result);

        return redirect()->route('lottery.edit', $lottery);
    }

    public function edit(Request $request, Lottery $lottery)
    {
        return view('lottery.edit', compact('lottery'));
    }

    public function update(Request $request, Lottery $lottery)
    {
        foreach ($request->lottery as $lotteryDetailId => $lotteryDetailData) {
            $lotteryDetail = LotteryDetail::find($lotteryDetailId);
            $lotteryDetail->update($lotteryDetailData);
        }

        $lottery->total_number = $lottery->detail->count();
        $lottery->total_price = $lottery->sumTotalPrice();
        $lottery->save();

        return redirect()->route('lottery.index');
    }
}

resources/views/lottery/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Lottery Api Demo</title>

    <script src="https://cdn.tailwindcss.com"></script>

    <style>
        table {
            width: 90%;
        }
        table th,td {
            border: 1px solid black;
            padding: 10px;
            text-align: center;
        }
        table input {
            border: 1px solid #ddd;
            border-radius: 5px;
            padding: 5px;
        }
    </style>
</head>
<body>
    <div class="p-20">
        <h1>upload lottery image (only jpg)</h1>
        <form method="POST" action="{{ route('lottery.store') }}" enctype="multipart/form-data">
            @csrf
            <input type="file" name="file" accept="image/jpeg" required />
            <div class="mt-4">
                <button type="submit" class="border rounded-lg py-2 px-10 hover:bg-green-700 hover:text-white">Upload</button>
            </div>
        </form>
    </div>
</body>
</html>

resources/views/lottery/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Lottery Api Demo</title>

    <script src="https://cdn.tailwindcss.com"></script>

    <style>
        table {
            width: 90%;
        }
        table th,td {
            border: 1px solid black;
            padding: 10px;
            text-align: center;
        }
        table input {
            border: 1px solid #ddd;
            border-radius: 5px;
            padding: 5px;
        }
    </style>
</head>
<body>
    <div class="grid grid-cols-2">
        <div>
            <div class="w-2/3">
                <img src="{{ $lottery->file_url }}" class="h-full">
            </div>
        </div>
        <div>
            <form method="POST" action="{{ route('lottery.update', $lottery) }}">
                @method('patch')
                @csrf
                <table>
                    <thead>
                        <tr>
                            <th colspan="2">เลขแทง</th>
                            <th colspan="2">ราคา</th>
                        </tr>
                        <tr>
                            <th>เลข</th>
                            <th>%</th>
                            <th>ราคา</th>
                            <th>%</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($lottery->detail as $row)
                        <tr>
                            <td><input type="text" name="lottery[{{ $row->id }}][number]" value="{{ $row->number }}" class="w-full"></td>
                            <td><span class="text-{{ $row->number_confidence > 90 ? 'green' : 'red' }}-500">{{ number_format($row->number_confidence,2) }}</span></td>
                            <td><input type="text" name="lottery[{{ $row->id }}][price]" value="{{ $row->price }}" class="w-full"></td>
                            <td><span class="text-{{ $row->number_confidence > 90 ? 'green' : 'red' }}-500">{{ number_format($row->price_confidence,2) }}</span></td>
                        </tr>
                        @endforeach
                    </tbody>
                    <tfoot>
                        <tr>
                            <th colspan="2" class="text-left">{{ $lottery->total_number }}</th>
                            <th colspan="2" class="text-left">{{ number_format($lottery->total_price,2) }}</th>
                        </tr>
                    </tfoot>
                </table>

                <div class="mt-4">
                    <button type="submit" class="border rounded-lg py-2 px-10 bg-green-300 hover:bg-green-700 hover:text-white">บันทึก</button>
                    <a href="/lottery" class="border rounded-lg py-3 px-10 bg-red-300 hover:bg-red-700 hover:text-white">ยกเลิก</a>
                </div>
            </form>
        </div>
    </div>
</body>
</html>

resources/views/lottery/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Lottery Api Demo</title>

    <script src="https://cdn.tailwindcss.com"></script>

    <style>
        table {
            margin: 0 auto;
            width: 90%;
        }
        table th,td {
            border: 1px solid black;
            padding: 10px;
            text-align: center;
        }
        table input {
            border: 1px solid #ddd;
            border-radius: 5px;
            padding: 5px;
        }
    </style>
</head>
<body>
    <div class="text-right mr-10 my-10">
        <a href="/lottery/create" class="border rounded-lg py-2 px-10 hover:bg-blue-700 hover:text-white">Create</a>
    </div>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Date</th>
                <th>Agent</th>
                <th>No.</th>
                <th>Total Number</th>
                <th>Total Price</th>
                <th>Api Provider</th>
                <th>Api Cost</th>
                <th>Created At</th>
                <th>View/Edit</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($lotteries as $lottery)
            <tr>
                <td>{{ $lottery->id }}</td>
                <td>{{ $lottery->drawing_date }}</td>
                <td>{{ $lottery->agent_no }}</td>
                <td>{{ $lottery->no }}</td>
                <td>{{ $lottery->total_number }}</td>
                <td>{{ number_format($lottery->total_price,2) }}</td>
                <td>{{ $lottery->api_provider }}</td>
                <td>{{ $lottery->api_cost }}</td>
                <td>{{ $lottery->created_at }}</td>
                <td><a href="/lottery/{{ $lottery->id }}/edit" class="border rounded-lg py-2 px-10 hover:bg-cyan-300 hover:text-white">View/Edit</a></td>
            </tr>
            @endforeach
        </tbody>
    </table>
</body>
</html>